version: "3"

services:
  ruby:
    container_name: "ruby_gabe"
    image: ruby:3.1.2-alpine
    ports:
      - "3010:3010"
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    stdin_open: true